In [ ]:
import pandas as pd
import sqlite3

from sqlalchemy import create_engine

In [ ]:
df = pd.read_csv("../data/processed/telco_cleaned.csv")

In [ ]:
conn = sqlite3.connect("../database/telco.db")
print("database connected successfully")

database connected successfully

In [ ]:
df.to_sql("customers", conn, if_exists="replace", index=False)

7043

In [ ]:
pd.read_sql("SELECT * FROM customers LIMIT 5", conn)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
query = """
SELECT contract,
AVG(monthlycharges)
FROM customers
GROUP BY contract;
"""

pd.read_sql(query, conn)

         contract  AVG(monthlycharges)
0  Month-to-month            66.398490
1        One year            65.048608
2        Two year            60.770413

In [ ]:
query = """
SELECT churn,
COUNT(*)
FROM customers
GROUP BY churn;
"""

result = pd.read_sql(query, conn)

result

  churn  COUNT(*)
0    No      5174
1   Yes      1869

In [ ]:
contract = "Month-to-month"

query = """
SELECT *
FROM customers
WHERE contract=?
"""

pd.read_sql(query, conn, params=(contract,))

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
2,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
3,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
4,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,9767-FFLEM,Male,0,No,No,38,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.50,2625.25,No
3871,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
3872,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.10,No
3873,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
3874,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [ ]:
pd.read_sql("EXPLAIN QUERY PLAN SELECT * FROM customers;", conn)

   id  parent  notused          detail
0   2       0      216  SCAN customers

In [ ]:
conn.execute(
"""
CREATE INDEX idx_contract
ON customers(contract);
"""
)

In [ ]:
query = """
SELECT paymentmethod,
COUNT(*)
FROM customers
GROUP BY paymentmethod;
"""

result = pd.read_sql(query, conn)

result

               paymentmethod  COUNT(*)
0  Bank transfer (automatic)      1544
1    Credit card (automatic)      1522
2           Electronic check      2365
3               Mailed check      1612

In [ ]:
query = """
SELECT internetservice,
AVG(tenure)
FROM customers
GROUP BY internetservice;
"""

result = pd.read_sql(query, conn)

result

  internetservice  AVG(tenure)
0             DSL    32.821561
1     Fiber optic    32.917959
2              No    30.547182

In [ ]:
query = """
SELECT MAX(monthlycharges)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   MAX(monthlycharges)
0               118.75

In [ ]:
query = """
SELECT MIN(monthlycharges)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   MIN(monthlycharges)
0                18.25

In [ ]:
query = """
SELECT AVG(monthlycharges)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   AVG(monthlycharges)
0            64.761692

In [ ]:
query = """
SELECT SUM(monthlycharges)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   SUM(monthlycharges)
0             456116.6

In [ ]:
query = """
SELECT COUNT(*)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   COUNT(*)
0      7043

In [ ]:
query = """
SELECT *
FROM customers
WHERE monthlycharges >
(
SELECT AVG(monthlycharges)
FROM customers
);
"""

result = pd.read_sql(query, conn)

result

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
2,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.10,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3918,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.10,No
3919,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
3920,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
3921,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
3922,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [ ]:
query = """
WITH churn_customers AS
(
SELECT *
FROM customers
WHERE churn = 'Yes'
)

SELECT *
FROM churn_customers;
"""

result = pd.read_sql(query, conn)

result

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
1,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
2,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,1699-HPSBG,Male,0,No,No,12,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Electronic check,59.80,727.80,Yes
1865,8775-CEBBJ,Female,0,No,No,9,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
1866,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
1867,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
1868,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [ ]:
query = """
SELECT customerid,
monthlycharges,

ROW_NUMBER()
OVER(ORDER BY monthlycharges DESC)
AS Rank

FROM customers;
"""

result = pd.read_sql(query, conn)

result

      customerid  monthlycharges  Rank
0     7569-NMZYQ          118.75     1
1     8984-HPEMB          118.65     2
2     5989-AXPUC          118.60     3
3     5734-EJKXG          118.60     4
4     8199-ZLLSA          118.35     5
...          ...             ...   ...
7038  0621-CXBKL           18.70  7039
7039  9945-PSVIP           18.70  7040
7040  0827-ITJPH           18.55  7041
7041  9764-REAFF           18.40  7042
7042  6823-SIDFQ           18.25  7043

[7043 rows x 3 columns]

In [ ]:
query = """
SELECT customerid,
monthlycharges,

RANK()
OVER(ORDER BY monthlycharges DESC)
AS Rank

FROM customers;
"""

result = pd.read_sql(query, conn)

result

      customerid  monthlycharges  Rank
0     7569-NMZYQ          118.75     1
1     8984-HPEMB          118.65     2
2     5989-AXPUC          118.60     3
3     5734-EJKXG          118.60     3
4     8199-ZLLSA          118.35     5
...          ...             ...   ...
7038  0621-CXBKL           18.70  7039
7039  9945-PSVIP           18.70  7039
7040  0827-ITJPH           18.55  7041
7041  9764-REAFF           18.40  7042
7042  6823-SIDFQ           18.25  7043

[7043 rows x 3 columns]

In [ ]:
query = """
SELECT customerid,
monthlycharges,

LAG(monthlycharges)
OVER(ORDER BY tenure)
AS PreviousCharge

FROM customers;
"""

result = pd.read_sql(query, conn)

result

      customerid  monthlycharges  PreviousCharge
0     4472-LVYGI           52.55             NaN
1     3115-CZMZD           20.25           52.55
2     5709-LVOEQ           80.85           20.25
3     4367-NUYAO           25.75           80.85
4     1371-DWPAZ           56.05           25.75
...          ...             ...             ...
7038  8468-FZTOE           74.35           55.65
7039  2274-XUATA           63.10           74.35
7040  7203-OYKCT          104.95           63.10
7041  2569-WGERO           21.15          104.95
7042  2234-XADUH          103.20           21.15

[7043 rows x 3 columns]

In [ ]:
query = """
SELECT customerid,
monthlycharges,

LEAD(monthlycharges)
OVER(ORDER BY tenure)
AS NextCharge

FROM customers;
"""

result = pd.read_sql(query, conn)

result

      customerid  monthlycharges  NextCharge
0     4472-LVYGI           52.55       20.25
1     3115-CZMZD           20.25       80.85
2     5709-LVOEQ           80.85       25.75
3     4367-NUYAO           25.75       56.05
4     1371-DWPAZ           56.05       19.85
...          ...             ...         ...
7038  8468-FZTOE           74.35       63.10
7039  2274-XUATA           63.10      104.95
7040  7203-OYKCT          104.95       21.15
7041  2569-WGERO           21.15      103.20
7042  2234-XADUH          103.20         NaN

[7043 rows x 3 columns]

In [ ]:
query = """
SELECT COUNT(*)
FROM customers
WHERE churn = 'Yes';
"""

result = pd.read_sql(query, conn)

result

   COUNT(*)
0      1869

In [ ]:
query = """
SELECT AVG(tenure)
FROM customers;
"""

result = pd.read_sql(query, conn)

result

   AVG(tenure)
0    32.371149

In [ ]:
query = """
SELECT customerid,
monthlycharges

FROM customers

ORDER BY monthlycharges DESC

LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

   customerid  monthlycharges
0  7569-NMZYQ          118.75
1  8984-HPEMB          118.65
2  5989-AXPUC          118.60
3  5734-EJKXG          118.60
4  8199-ZLLSA          118.35
5  9924-JPRMC          118.20
6  2889-FPWRM          117.80
7  3810-DVDQQ          117.60
8  9739-JLPQJ          117.50
9  2302-ANTDP          117.45

In [ ]:
query = """
SELECT paymentmethod,
COUNT(*)

FROM customers

GROUP BY paymentmethod;
"""

result = pd.read_sql(query, conn)

result

               paymentmethod  COUNT(*)
0  Bank transfer (automatic)      1544
1    Credit card (automatic)      1522
2           Electronic check      2365
3               Mailed check      1612

In [ ]:
query = """
SELECT internetservice,
COUNT(*)

FROM customers

GROUP BY internetservice;
"""

result = pd.read_sql(query, conn)

result

  internetservice  COUNT(*)
0             DSL      2421
1     Fiber optic      3096
2              No      1526

In [ ]:
query = """
EXPLAIN QUERY PLAN

SELECT paymentmethod,
COUNT(*)

FROM customers

GROUP BY paymentmethod;
"""

result = pd.read_sql(query, conn)

result

   id  parent  notused                        detail
0   6       0      216                SCAN customers
1   8       0        0  USE TEMP B-TREE FOR GROUP BY